### ISSUE TITLE
As a team manager, I want to be able to look at other managers' teams so that I can set my own team accordingly each week.

### ISSUE THREAD

**Issue by kbrandonle** [wsu-cpts489-fa20/bp-football#2]
13 Points
- [x] Edit draft system with new API
Now that we have the ESPN API setup, we can create a draft system where players pick from the large pool of NFL players. As an NFL player is selected, that player becomes unavailable to other managers in the league.

- [ ] Create a league page where managers can see all other managers in the league and which players they have in their roster. 
The layout will display a table of all the managers in the league. Clicking on a view button for each manager will reveal the players on that manager's  team.

**Comment by chundhau** [comment]
Could you please flesh out more what is meant by "Establish a friend id list?" Does that mean that I can search for friends by name, id, etc.? What about removing friends from my list?

**Comment by kbrandonle** [comment]
Revised this milestone to reflect a better end product. The team feels that a friend system isn't as important as revising the team management system. The difficulty of this revised milestone may be even more challenging that the original, so we must be diligent.
