### ISSUE TITLE
As a team manager, I want to be able to see my profile/achievements so that I can see how well I performed in the current season.

### ISSUE THREAD

**Issue by kbrandonle** [wsu-cpts489-fa20/bp-football#3]
8 points

- [x] Record weekly scores

- [x] Set up a few achievements

- [x] Establish public user profile

**Comment by chundhau** [comment]
Some clarification of acceptance criteria would be helpful. What is an "achievement?" What is involved in setting one up? What are the contents of a "public user profile" and how can I "establish" one? Note that creating a public user profile may need to be a separate user story.
