### ISSUE TITLE
As a team manager, I want to be able to set my line up so that I can choose which players’ score will count for that week.

### ISSUE THREAD

**Issue by kbrandonle** [wsu-cpts489-fa20/bp-football#4]
3 points

- [x] Create team positions (QB, RB, WR, BE, etc...)

- [ ] Manager can only move players to their respective roles

- [x] If a game has already started, that player cannot be moved for the rest of the week

**Comment by chundhau** [comment]
- It appears this story assumes the manager has already drafted players. It seems that the "draft" is an important step in this process that needs clarification--probably as a separate user story.
- Is the idea to drag/drop players to positions or to select each position from a drop-down of available players at that position?

**Comment by kbrandonle** [comment]
Havent quite implemented moving players around yet, however the user is able to see which players are starting and which are benched for the current week.
