### ISSUE TITLE
As a commissioner, I want to upload each team manager's player roster after an offline draft, so that the league games can start.

### ISSUE THREAD

**Issue by kbrandonle** [wsu-cpts489-fa20/bp-football#5]
3 points

- [x] Be able to assign a commissioner

- [x] Commissioner assigns each manager with players they selected

- [x] Commissioner is able to assign league settings

**Comment by chundhau** [comment]
- I am unclear on what is meant by "assign managers with football players." Please clarify
- How can a commissioner add football players to be drafted? Is this a file upload of some sort? Should this be a separate user story?
- How do managers participate in a draft? Is that a separate user story?
