### ISSUE TITLE
As an team manager, I want to be able to make an account so that I can keep track of my league history

### ISSUE THREAD

**Issue by kbrandonle** [wsu-cpts489-fa20/bp-football#6]
1 point

- [x] Cannot join a league unless you have an account

- [x] User can change account information
    - [x] phone number
    - [x] team name
    - [x] email
    - [x] security question

- [x] User can look at game history for current season.
- [x] A user's game history will show the previous weekly matchups for the current season. 
    - [x] user score vs. opponent score
    - [x] win/loss record
    - [x] week

**Comment by chundhau** [comment]
Please specify what account info you will require. Remember that account creation and editing will be part of the base code you get. Also, please specify what "game history" looks like. Is this part of the user's account? I'm assuming it's non-editable.
